### ISSUE TITLE
enhancement: timestamp in filename

### ISSUE THREAD

**Issue by akshayitzme** [wahni-green/genie#5]
### Current Behavior
Files are named in the pattern `screen_recording+unique_id.mp4`

### Proposed Improvement:
I propose replacing the initial chunk of the filename `screen_recording` to `genie-screen-rec`. followed by the timestamp string.
Eg: `genie-screen-rec-1697368455479.mp4`

### Benefits
This change would help the users to easily identify media files that's generated by Genie. The trailing timestamp string would make each filenames unique. It also leaves a possibility to trace back when the file is created. 

@rtdany10 , If you approve this proposal, please assign this issue to me as I would like to work on this.

**Comment by rtdany10** [comment]
Also add a read-only check box in File to flag them?

**Comment by akshayitzme** [comment]
> Also add a read-only check box in File to flag them?

Yes. 
In addition to that, I'm adding the logic to create a new Folder for `Genie` in the File List to store the recordings in it. 
I believe this will be a better way to organize the files. Also we can shorten the output filename to `screen-rec-1697368455479.mp4`
